create table if not exists public.knowledge_nodes (
  id text primary key,
  name text not null,
  kind text not null check (kind in ('project', 'note', 'skill', 'tool', 'file')),
  description text not null default '',
  group_name text not null default 'INNER',
  val double precision not null default 8,
  color text not null default '#55f2c0',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_links (
  id bigint generated by default as identity primary key,
  source_id text not null references public.knowledge_nodes(id) on delete cascade,
  target_id text not null references public.knowledge_nodes(id) on delete cascade,
  relation text not null default 'связано с',
  created_at timestamptz not null default now(),
  unique (source_id, target_id),
  check (source_id <> target_id)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists knowledge_nodes_updated_at on public.knowledge_nodes;
create trigger knowledge_nodes_updated_at
before update on public.knowledge_nodes
for each row execute procedure public.set_updated_at();

alter table public.knowledge_nodes enable row level security;
alter table public.knowledge_links enable row level security;

-- MVP policies. Replace these with authenticated-user policies before public launch.
drop policy if exists "public read nodes" on public.knowledge_nodes;
create policy "public read nodes" on public.knowledge_nodes for select using (true);

drop policy if exists "public write nodes" on public.knowledge_nodes;
create policy "public write nodes" on public.knowledge_nodes for all using (true) with check (true);

drop policy if exists "public read links" on public.knowledge_links;
create policy "public read links" on public.knowledge_links for select using (true);

drop policy if exists "public write links" on public.knowledge_links;
create policy "public write links" on public.knowledge_links for all using (true) with check (true);
